#!/usr/bin/env bash
#
#/ command: toolchain-build-console:deploy: "Deploy the toolchain's build console"
#
#/ usage: rerun toolchain-build-console:deploy [options]
#
#/ rerun env variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option variables: 

# Read module function library.
. $RERUN_MODULE_DIR/lib/functions.sh || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

# Error handling
# ---------------
# * Trap calls `rerun_die` with standard message.
# * Exit upon command errors or accessing unset variables.
#   * See [set](http://ss64.com/bash/set.html)
trap 'rerun_die "*** command failed: toolchain-build-console:deploy. ***"' ERR
set -o nounset -o pipefail

# Parse the command options.
[[ -r $RERUN_MODULE_DIR/commands/deploy/options.sh ]] && {
    . $RERUN_MODULE_DIR/commands/deploy/options.sh || rerun_die "Failed loading options parser."
    rerun_options_parse "$@"
}


# ------------------------------
# Your implementation goes here.
# ------------------------------

# Make sure the build console is down:
rerun toolchain-build-console:stop

# Install the build console's packages:
rerun toolchain-build-console:install

# Start the build console:
rerun toolchain-build-console:start

# Configure the build console:
rerun toolchain-build-console:configure

# Run the build jobs:
rerun toolchain-build-console:build-now

exit $?

# Done
