#!/usr/bin/env bash
#
#/ command: booking-database-server:install: "Installs packages needed by the Booking application MySQL server"
#
#/ usage: rerun booking-database-server:install  --data-package-file <> 
#
#/ rerun env variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option variables: DATA_PACKAGE_FILE

# Read module function library.
. $RERUN_MODULE_DIR/lib/functions.sh || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

# Error handling
# ---------------
# * Trap calls `rerun_die` with standard message.
# * Exit upon command errors or accessing unset variables.
#   * See [set](http://ss64.com/bash/set.html)
trap 'rerun_die "*** command failed: booking-database-server:install. ***"' ERR
set -o nounset -o pipefail

# Parse the command options.
[[ -r $RERUN_MODULE_DIR/commands/install/options.sh ]] && {
    . $RERUN_MODULE_DIR/commands/install/options.sh || rerun_die "Failed loading options parser."
    rerun_options_parse "$@"
}


# ------------------------------
# Your implementation goes here.
# ------------------------------

# Install the MySQL server and the Booking data packages.
rerun mysql:install
rerun rpm:upgrade --package-file $DATA_PACKAGE_FILE

exit $?

# Done
