#!/usr/bin/env bash
#
#/ command: booking-application-server:remove: "Remove the Booking Application Server"
#
#/ usage: rerun booking-application-server:remove [ --cleanup <false>] 
#
#/ rerun env variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option variables: CLEANUP

# Read module function library.
. $RERUN_MODULE_DIR/lib/functions.sh || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

# Error handling
# ---------------
# * Trap calls `rerun_die` with standard message.
# * Exit upon command errors or accessing unset variables.
#   * See [set](http://ss64.com/bash/set.html)
trap 'rerun_die "*** command failed: booking-application-server:remove. ***"' ERR
set -o nounset -o pipefail

# Parse the command options.
[[ -r $RERUN_MODULE_DIR/commands/remove/options.sh ]] && {
    . $RERUN_MODULE_DIR/commands/remove/options.sh || rerun_die "Failed loading options parser."
    rerun_options_parse "$@"
}


# ------------------------------
# Your implementation goes here.
# ------------------------------


rerun jboss-as:stop
rerun rpm:erase --package-name seam-booking-rpm
rerun rpm:erase --package-name mysql-connector-rpm
rerun rpm:erase --package-name jboss-as-config-rpm
rerun jboss-as:remove --cleanup ${CLEANUP}

exit $?

# Done
