# Generated by stubbs:add-option. Do not edit, if using stubbs.
# Created: Tue Nov 20 14:34:56 PST 2012
#
#/ usage: booking-application-server:install-module [ --build <false>] [ --release <1>] 

# _rerun_options_parse_ - Parse the command arguments and set option variables.
#
#     rerun_options_parse "$@"
#
# Arguments:
#
# * the command options and their arguments
#
# Notes:
# 
# * Sets shell variables for any parsed options.
# * The "-?" help argument prints command usage and will exit 2.
# * Return 0 for successful option parse.
#
rerun_options_parse() {
    
    while [ "$#" -gt 0 ]; do
        OPT="$1"
        case "$OPT" in
            --build) rerun_option_check $# ; BUILD=$2 ; shift ;;
            --release) rerun_option_check $# ; RELEASE=$2 ; shift ;;
            # help option
            -?)
                rerun_option_usage
                exit 2
                ;;
            # end of options, just arguments left
            *)
              break
        esac
        shift
    done

    # Set defaultable options.
    [ -z "$BUILD" ] && BUILD="false"
    [ -z "$RELEASE" ] && RELEASE="1"
    # Check required options are set

    # If option variables are declared exportable, export them.
    export BUILD
    export RELEASE
    #
    return 0
}


# Initialize the options variables to null.
BUILD=
RELEASE=


