#!/usr/bin/env bash
#
#/ command: jboss-as-rpm:build-now: "Run the Jenkins build job"
#
#/ usage: rerun jboss-as-rpm:build-now [options]
#
#/ rerun env variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option variables: 

# Read module function library.
. $RERUN_MODULE_DIR/lib/functions.sh || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

# Error handling
# ---------------
# * Trap calls `rerun_die` with standard message.
# * Exit upon command errors or accessing unset variables.
#   * See [set](http://ss64.com/bash/set.html)
trap 'rerun_die $? "*** command failed: jboss-as-rpm:build-now. ***"' ERR
set -o nounset -o pipefail

# Parse the command options.
[[ -r $RERUN_MODULE_DIR/commands/build-now/options.sh ]] && {
    . $RERUN_MODULE_DIR/commands/build-now/options.sh || rerun_die "Failed loading options parser."
    rerun_options_parse "$@"
}


# ------------------------------
# Your implementation goes here.
# ------------------------------

for FILE in $(ls -d $RERUN_MODULE_DIR/jobs/*/config.xml)
do
  JOBNAME=$(basename $(dirname $FILE))
  rerun jenkins:build-now --jobname $JOBNAME
done

exit $?

# Done
