#!/usr/bin/env bash
#
#/ command: booking-database-server:erase: "Erase the database server packages from the system"
#
#/ usage: rerun booking-database-server:erase [options]
#
#/ rerun env variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option variables: 

# Read module function library.
. $RERUN_MODULE_DIR/lib/functions.sh || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

# Error handling
# ---------------
# * Trap calls `rerun_die` with standard message.
# * Exit upon command errors or accessing unset variables.
#   * See [set](http://ss64.com/bash/set.html)
trap 'rerun_die "*** command failed: booking-database-server:erase. ***"' ERR
set -o nounset -o pipefail

# Parse the command options.
[[ -r $RERUN_MODULE_DIR/commands/erase/options.sh ]] && {
    . $RERUN_MODULE_DIR/commands/erase/options.sh || rerun_die "Failed loading options parser."
    rerun_options_parse "$@"
}


# ------------------------------
# Your implementation goes here.
# ------------------------------

# Erase the Booking application's MySQL data package:
rerun rpm:erase --package-name booking-mysql-data

# Erase the MySQL server installation from the system and remove the database files, etc:
rerun mysql:remove --cleanup true

exit $?

# Done
