#!/usr/bin/env bash
#
#/ command: toolchain-deploy-console:configure: "configure the deploy console"
#
#/ usage: rerun toolchain-deploy-console:configure [options]
#
#/ rerun env variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option variables: 

# Read module function library.
. $RERUN_MODULE_DIR/lib/functions.sh || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

# Error handling
# ---------------
# * Trap calls `rerun_die` with standard message.
# * Exit upon command errors or accessing unset variables.
#   * See [set](http://ss64.com/bash/set.html)
trap 'rerun_die "*** command failed: toolchain-deploy-console:configure. ***"' ERR
set -o nounset -o pipefail

# Parse the command options.
[[ -r $RERUN_MODULE_DIR/commands/configure/options.sh ]] && {
    . $RERUN_MODULE_DIR/commands/configure/options.sh || rerun_die "Failed loading options parser."
    rerun_options_parse "$@"
}


# ------------------------------
# Your implementation goes here.
# ------------------------------

# Install the plug-ins required by the example builds.
#rerun rundeck:install-plugin --plugin-name somePlugin?

# Configure the somePlugin? plugin.
#rerun rundeck:configure-rundeck-plugin

# Restart Rundeck to enable the configuration (if we add any above).
#rerun rundeck:restart

# Create the Jenkins jobs:
rerun booking-application-server:create-jobs


exit $?

# Done
