#!/usr/bin/env bash
#
#/ command: toolchain-deploy-console:configure: "configure the deploy console"
#
#/ usage: rerun toolchain-deploy-console:configure [options]
#
#/ rerun env variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option variables: 

# Read module function library.
. $RERUN_MODULE_DIR/lib/functions.sh || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

# Error handling
# ---------------
# * Trap calls `rerun_die` with standard message.
# * Exit upon command errors or accessing unset variables.
#   * See [set](http://ss64.com/bash/set.html)
trap 'rerun_die "*** command failed: toolchain-deploy-console:configure. ***"' ERR
set -o nounset -o pipefail

# Parse the command options.
[[ -r $RERUN_MODULE_DIR/commands/configure/options.sh ]] && {
    . $RERUN_MODULE_DIR/commands/configure/options.sh || rerun_die "Failed loading options parser."
    rerun_options_parse "$@"
}


# ------------------------------
# Your implementation goes here.
# ------------------------------

# Create the example Rundeck jobs.
rerun booking-application-server:create-deploy-jobs
rerun booking-database-server:create-deploy-jobs

# Setup the Rundeck user as an authorized key for the toolchain user.
TYPE=$(sudo cat  ~rundeck/.ssh/id_rsa.pub | cut -d' ' -f1 | cut -d- -f2)
PUBLIC_KEY=$(sudo cat  ~rundeck/.ssh/id_rsa.pub | cut -d' ' -f2)
COMMENT=$(sudo cat  ~rundeck/.ssh/id_rsa.pub | cut -d' ' -f3-)

rerun ssh:add-authorized-key --public-key "${PUBLIC_KEY}" --type ${TYPE} --comment "${COMMENT}"

# Setup localhost as a known host of the Rundeck user
HOST_PUBLIC_KEY=$(cat /etc/ssh/ssh_host_${TYPE}_key.pub | cut -d' ' -f2)
sudo -u rundeck rerun ssh:add-host-key --host-key "${HOST_PUBLIC_KEY}" --type ${TYPE} --hostname localhost

exit $?

# Done
