#!/usr/bin/env bash
#
#/ command: toolchain-deploy-console:deploy: "deploy the deploy console"
#
#/ usage: rerun toolchain-deploy-console:deploy [options]
#
#/ rerun env variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option variables: 

# Read module function library.
. $RERUN_MODULE_DIR/lib/functions.sh || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

# Error handling
# ---------------
# * Trap calls `rerun_die` with standard message.
# * Exit upon command errors or accessing unset variables.
#   * See [set](http://ss64.com/bash/set.html)
trap 'rerun_die "*** command failed: toolchain-deploy-console:deploy. ***"' ERR
set -o nounset -o pipefail

# Parse the command options.
[[ -r $RERUN_MODULE_DIR/commands/deploy/options.sh ]] && {
    . $RERUN_MODULE_DIR/commands/deploy/options.sh || rerun_die "Failed loading options parser."
    rerun_options_parse "$@"
}


# ------------------------------
# Your implementation goes here.
# ------------------------------

# Make sure the deploy console is down:
rerun toolchain-deploy-console:stop

# Install the deploy console's packages:
rerun toolchain-deploy-console:install

# Start the deploy console:
rerun toolchain-deploy-console:start

# Configure the deploy console:
rerun toolchain-deploy-console:configure


exit $?

# Done
