#!/usr/bin/env bash
#
#/ command: seam-examples:create-jobs: "Create the Jenkins job(s) for the Seam Examples build process"
#
#/ usage: rerun seam-examples:create-jobs [ --jenkins-url <http://localhost:8080>] 
#
#/ rerun env variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option variables: JENKINS_URL

# Read module function library.
. $RERUN_MODULE_DIR/lib/functions.sh || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

# Error handling
# ---------------
# * Trap calls `rerun_die` with standard message.
# * Exit upon command errors or accessing unset variables.
#   * See [set](http://ss64.com/bash/set.html)
trap 'rerun_die "*** command failed: seam-examples:create-jobs. ***"' ERR
set -o nounset -o pipefail

# Parse the command options.
[[ -r $RERUN_MODULE_DIR/commands/create-jobs/options.sh ]] && {
    . $RERUN_MODULE_DIR/commands/create-jobs/options.sh || rerun_die "Failed loading options parser."
    rerun_options_parse "$@"
}


# ------------------------------
# Your implementation goes here.
# ------------------------------

for FILE in $(ls -d $RERUN_MODULE_DIR/jobs/*/config.xml)
do
  JOBNAME=$(basename $(dirname $FILE))
  rerun jenkins:create-job --jobname $JOBNAME --file $FILE
done

exit $?

# Done
