#!/usr/bin/env bash
#
#/ command: booking-application-server:create-deploy-jobs: "Create deploy jobs within the Deploy Console"
#
#/ usage: rerun booking-application-server:create-deploy-jobs [options]
#
#/ rerun env variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option variables: 

# Read module function library.
. $RERUN_MODULE_DIR/lib/functions.sh || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

# Error handling
# ---------------
# * Trap calls `rerun_die` with standard message.
# * Exit upon command errors or accessing unset variables.
#   * See [set](http://ss64.com/bash/set.html)
trap 'rerun_die $? "*** command failed: booking-application-server:create-deploy-jobs. ***"' ERR
set -o nounset -o pipefail

# Parse the command options.
[[ -r $RERUN_MODULE_DIR/commands/create-deploy-jobs/options.sh ]] && {
    . $RERUN_MODULE_DIR/commands/create-deploy-jobs/options.sh || rerun_die "Failed loading options parser."
    rerun_options_parse "$@"
}


# ------------------------------
# Your implementation goes here.
# ------------------------------

rerun rundeck:create-project  --name dtolabs-toolchain-example5

for FILE in $(ls -d $RERUN_MODULE_DIR/jobs/*/job.xml)
do
  rerun rundeck:create-job  --file $FILE
done

exit $?

# Done
