#!/usr/bin/env bash
#
#/ command: booking-application-server:deploy: "Deploy the Booking Application Server"
#
#/ usage: rerun booking-application-server:deploy  --jboss-as-package-file <>  --jboss-as-config-package-file <>  --mysql-connector-package-file <>  --seam-booking-package-file <> 
#
#/ rerun env variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option variables: JBOSS_AS_PACKAGE_FILE JBOSS_AS_CONFIG_PACKAGE_FILE MYSQL_CONNECTOR_PACKAGE_FILE SEAM_BOOKING_PACKAGE_FILE

# Read module function library.
. $RERUN_MODULE_DIR/lib/functions.sh || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

# Error handling
# ---------------
# * Trap calls `rerun_die` with standard message.
# * Exit upon command errors or accessing unset variables.
#   * See [set](http://ss64.com/bash/set.html)
trap 'rerun_die "*** command failed: booking-application-server:deploy. ***"' ERR
set -o nounset -o pipefail

# Parse the command options.
[[ -r $RERUN_MODULE_DIR/commands/deploy/options.sh ]] && {
    . $RERUN_MODULE_DIR/commands/deploy/options.sh || rerun_die "Failed loading options parser."
    rerun_options_parse "$@"
}


# ------------------------------
# Your implementation goes here.
# ------------------------------

rerun booking-application-server: stop

rerun booking-application-server: install \
      --jboss-as-package-file ${JBOSS_AS_PACKAGE_FILE} \
      --jboss-as-config-package-file ${JBOSS_AS_CONFIG_PACKAGE_FILE} \
      --mysql-connector-package-file ${MYSQL_CONNECTOR_PACKAGE_FILE} \
      --seam-booking-package-file ${SEAM_BOOKING_PACKAGE_FILE}

rerun booking-application-server: configure

rerun booking-application-server: start

exit $?

# Done
