#!/usr/bin/env bash
#
#/ command: booking-application-server:deploy: "Deploy the Booking Application Server"
#
#/ usage: rerun booking-application-server:deploy [options]
#
#/ rerun env variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option variables: 

# Read module function library.
. $RERUN_MODULE_DIR/lib/functions.sh || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

# Error handling
# ---------------
# * Trap calls `rerun_die` with standard message.
# * Exit upon command errors or accessing unset variables.
#   * See [set](http://ss64.com/bash/set.html)
trap 'rerun_die "*** command failed: booking-application-server:deploy. ***"' ERR
set -o nounset -o pipefail

# Parse the command options.
[[ -r $RERUN_MODULE_DIR/commands/deploy/options.sh ]] && {
    . $RERUN_MODULE_DIR/commands/deploy/options.sh || rerun_die "Failed loading options parser."
    rerun_options_parse "$@"
}


# ------------------------------
# Your implementation goes here.
# ------------------------------

rerun booking-application-server: stop
rerun booking-application-server: install
rerun booking-application-server: configure
rerun booking-application-server: start

exit $?

# Done
